### PR TITLE
Fix the constructor to create db and/or db table only when necessary

### PR DESCRIPTION
**Pull request by aitorvs**
##### Proposed Changed

Refactor the `DatabaseHelper` constructor to call `CREATE TABLE IF NOT EXISTS` only when necessary.

``` java
        if (columns != null && (!databaseExists(context, databaseName) || !tableExists(table))) {
            String createStatement = String.format("CREATE TABLE IF NOT EXISTS %s (%s)", table, columns);
            getWritableDatabase().execSQL(createStatement);
        }
```

### CODE REVIEW

**Comment by janheinrichmerker** [comment]
I don't think this has any advantage to the SQL implementation as it already checks if the table exists (`IF NOT EXISTS`). At least as far as I understand SQL the current implementation should actually be faster as it doesn't need to execute one extra SQL query to check if the table exists but instead does the whole thing in one SQL call.
You should make a little benchmark to test this if you really think this would speed up the table creation performance.

**Comment by aitorvs** [comment]
There are two things with the previous code (not completely related to efficiency aspects):

**1)**

``` java
...
getWritableDatabase(); //This will invoke onUpgrade if necessary
...
```

That line is not necessary at all. `onUpgrade` will be called as soon as the constructor `DatabaseHelper` calls super (and when the db and/or table do not exist, etc.)

**2)**
The  creation `IF NOT EXISTS` calls `getWritableDatabase` that locks the database. I wanted to avoid that and that's why I check db and table using only `getPath` and `getReadableDatabase` instead. I think it is better when having producer-consumer**s** on the db.

I think 1) should be implemented (removing that useless call). Bullet 2) might be arguable.

**Comment by janheinrichmerker** [comment]
You are right about **1)**. Didn't know that.

Regarding **2)** I think the blocking execution when the table already exists will be so short that it wouldn't help much to replace it with a custom implementation. Either way I think you have more experience with SQLite databases so I leave that decision up to you.

**Comment by aitorvs** [comment]
Yeah, after your comment I am also hesitant about **2)**. It really is a corner case and anyway I think write access on the database should be done synchronously anyway by whoever uses the library.
I can remove it and create another PR with only **1)** if you want.

**Comment by janheinrichmerker** [comment]
Yup, that would be great!

**Comment by aitorvs** [comment]
I gave it another thought and maybe is good to keep the PR as is. Let me know what you think.

The issue is that a `DatabaseHelper` instance is created for every `Query`. The `SELECT` queries are the important ones here (read access).

The way I see it, in a database we should be able to have one producer (write) and multiple consumers (read). Potentially being those consumers in different threads. `SELECT` operations on the database do not lock it and so they present no problem whatsoever while multi-threading.
However, as it is now in Inquiry, **all** database accesses, both read and write, go through the `Query` object that also creates always a `DatabaseHelper` instance, and its constructor always calls `getWritableDatabase()` when performing the `CREATE TABLE IF NOT EXISTS` action.
This is not a corner case anymore, as different threads, reading off the db simultaneously would clash and throw `SQLiteDatabaseLockedException`.

The PR proposes the same check but without `getWritableDatabase()` -- without locking the database. Allowing for concurrent `SELECT` access.

**Comment by janheinrichmerker** [comment]
Yeah ok, I didn't know that. I'll merge it.

**Pull request merged**
